image:
  - Visual Studio 2015
  - Visual Studio 2017

build:
  project: fabtests.sln

configuration:
  - Debug-v140
  - Debug-v141
  - Release-v140
  - Release-v141

matrix:
  exclude:
    - configuration: Debug-v141
      image: Visual Studio 2015
    - configuration: Release-v141
      image: Visual Studio 2015

install:
  - cd ..
  - git clone https://github.com/ofiwg/libfabric
  - cd libfabric
  - ps: .appveyor.ps1 -Verbose
  - msbuild libfabric.sln
  - set PATH=%CD%\x64\%CONFIGURATION%;%PATH%
  - cd ..\fabtests

test_script:
  - set PATH=%CD%\x64\%CONFIGURATION%;%PATH%
  - set FI_PROVIDER=sockets
  - scripts\runfabtests.cmd
