dist: trusty
sudo: false
language: c
compiler:
    - gcc
    - clang
os:
    - osx
    - linux

env:
    global:
        - CPPFLAGS="-Wall -Werror"
        - CFLAGS="-Wall -Werror"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;
      brew upgrade automake || true; brew upgrade libtool || true;
    fi
install:
    - set -e
    - git clone https://github.com/ofiwg/libfabric.git
    - cd libfabric
    - ./autogen.sh
    - ./configure --prefix=$HOME
    - make
    - make install
    - cd ..
    - export LDFLAGS="-L$HOME/lib"
    - export CPPFLAGS="-I$HOME/include"
script:
    - ./autogen.sh
    - ./configure --prefix=$HOME
    - make
    - make install
    - make dist
    - set +e    # Disable exit on failure so that we don't exit when just one test fails
    - make test
